Emails
Orble-Tea/munch-website pull request #14
Opened 2024-07-01 15:26 UTC by jaimanm

********DO NOT REVIEW THIS PR YET, I'M OPENING THIS TO USE THE GITHUB ACTIONS DEPLOYMENT PREVIEW.********

This PR is for getting the contact page back up again. This means that most the work here involves making sure that we can send an email to info@orble-tea.com when the form on the page is submitted.

2025-01-12 20:16 UTC, SilasStokes commented on src/pages/api/send-email.js
> +  return new Response(JSON.stringify({ message: "Hello World" }));
Can we remove hello world? Does this function need to exist?

2025-01-12 20:44 UTC, SilasStokes commented
![Screenshot 2025-01-12 at 12 43 26](https://github.com/user-attachments/assets/d6287815-e592-4386-bf84-5b1e54521555)
when i click on the contact page i get a warning that there was too much recursion in the console. Can you investigate?

2025-01-12 20:52 UTC, SilasStokes requested changes

2025-01-12 20:52 UTC, SilasStokes commented on src/pages/api/send-email.js
> +  const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY;
can we pull this API key on website load so that way we don't have to click the email button to find out the env is bad?

2025-01-12 20:52 UTC, SilasStokes commented on src/pages/api/send-email.js
> +  console.log(response.status, response.statusText);
Do these console logs get removed on release builds? If not, lets remove them.

2025-01-12 20:52 UTC, SilasStokes commented on src/pages/dumpling.astro
> +        >GET STARTED</button
Not sure what is going on with this page showing up in the diff - is this code being moved from somewhere else? anyway it looks like this button has white text on the deployed website and here the text is black. Lets get that fixed.

2025-01-13 01:00 UTC, jaimanm commented on src/pages/api/send-email.js
> +  const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY;
I think we should retrieve the key in the POST request. Reasons:

- it keeps the API key on the server side, since onLoad is a client-side event
- it only retrieves the key when an email is being sent, so the key is not just sitting there if the user is not going to contact us
- reduces the amount of things being done on website load, which keeps the website from slowing down

2025-01-13 01:03 UTC, jaimanm commented on src/pages/dumpling.astro
> +        >GET STARTED</button
I'm not sure why it did this, but I'll change it back to what it was

2025-01-13 01:11 UTC, jaimanm commented
> when i click on the contact page i get a warning that there was too much recursion in the console. Can you investigate?

traced it back to an infinite recursive function, and fixed it

2025-01-13 03:52 UTC, SilasStokes commented on src/pages/api/send-email.js
> +  const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY;
sounds good. I am happy with that reasoning.

2025-01-13 03:56 UTC, SilasStokes commented on README.md
> +cp .env.example .env
Where is the .env.example file?

2025-01-13 03:58 UTC, SilasStokes commented on src/components/common/BasicScripts.astro
> +    // applyTheme("light");
Should this line be removed?

2025-01-14 01:32 UTC, aekang12 approved these changes

2025-01-14 01:32 UTC, aekang12 commented on src/pages/api/send-email.js
> +    body: JSON.stringify(emailData),
Do you do any validation/sanitization of the form input anywhere? if not it's a lower priority task but it might be good practice to validate the email address format/make sure required fields aren't empty/sanitize content (i.e. make sure there's no executable code) before submitting the post request. otherwise everything looks good to me!

2025-01-20 18:40 UTC, aekang12 requested changes

2025-01-20 18:40 UTC, aekang12 commented on src/pages/contact.astro
> +    }
It'd be good to check for HTML content too (for ex. you could use an <a> tag to disguise a malicious link). I think often instead of throwing an error, ppl escape/replace tags like in this [example](https://stackoverflow.com/questions/2794137/sanitizing-user-input-before-adding-it-to-the-dom-in-javascript). Or you could try [DOMPurify](https://github.com/cure53/DOMPurify).

Btw i don't actually know if any of this is actually explicitly necessary (maybe sendgrid/astro do some degree of sanitization already, or maybe sendgrid doesn't even render emails as HTML content) Regardless it's still good practice to always sanitize user input. But when you try sending HTML content does it actually do anything when it renders the email? just wondering.

2025-01-25 16:44 UTC, aekang12 approved these changes
👍

2025-01-28 03:36 UTC, merged